### ISSUE TITLE
TestServer.java doesn't work

### ISSUE THREAD

**Issue by artemik** [pcdv/jocket#6]
Software caused connection abort: socket write error

```
Exception in thread "main" java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:134)
	at java.io.DataOutputStream.writeInt(DataOutputStream.java:199)
	at jocket.net.ServerJocket.accept(ServerJocket.java:76)
```

**Comment by pcdv** [comment]
Sorry, missed the notification. What did you do to get this error? Is it reproducible?

A real socket is used for the handshake between client from server. 

Probably your network setup is not compatible with the way the socket is initialized, i.e.

ServerJocket:
    srv.bind(new InetSocketAddress(InetAddress.getByName(null), port));

JocketSocket:
    Socket s = new Socket(InetAddress.getByName(null), port);

I admit I don't precisely remember why it is initialized this way :)

**Comment by pcdv** [comment]
Closing after 7 years inactivity :)
